### ISSUE TITLE
Meaning of Trimming Stringency levels

### ISSUE THREAD

**Issue by ammaraziz** [gear-genomics/tracy#12]
Hello,

Tracy looks like a fantastic CLI, thank you for creating and maintaining it. 

Can you please provide more details on the stringency `-t` option in the `assembly` subcommand. I am guessing 9 is the highest, 1 is the lowest. It would be great to know what the difference between stringency `4` and `5`, and if the trimming is at the start/end only or will trimming happen on each trace/base. 

I notice the `decompose` subcommand includes additional trimming parameters (trimLeft and trimRight), I think these would be handy to include in `assembly` too. 

Thank you,

Ammar

**Comment by tobiasrausch** [comment]
The assembly module works on multiple traces. Thus, trimLeft and trimRight would require an array of numbers, one for each trace. To avoid this we created a single trimming stringency parameter, the higher the more aggressive is the trimming. Tracy is basically trimming the trace from the left and from the right until the normalized base quality is higher than the trimming threshold.

**Comment by ammaraziz** [comment]
Hi

Thanks for clearing that up. 

Would the issue you described still exist if a sliding window approach is used, similar to approaches used in cleaning fastq reads? For example a 3bp sliding window that averages the quality and cuts when the perbase quality drops below the trimming threshold.

As you probably know this approach is used in trimmomatic and other fastq trimmers.

Thanks!

Ammar

**Comment by tobiasrausch** [comment]
Sorry, I obviously forgot to reply. We don't do any trimming "inside" the traces. Only from the left and right end.
