### ISSUE TITLE
Kernel too old

### ISSUE THREAD

**Issue by roomfortwo** [gear-genomics/tracy#13]
Hello there, 
I was getting started with Tracy and the following error comes when I try to run the program from the conda installation and the precompiled binary,

`
(base) [larteag7@apolo banano-cultivables]$ conda create -n sangering bioconda::tracy bioconda::seqtk
(sangering) [larteag7@apolo banano-cultivables]$ tracy basecall -f fastq B100_907R.ab1                                                     
FATAL: kernel too old
Aborted
(sangering) [larteag7@apolo banano-cultivables]$ tracy --help
FATAL: kernel too old
Aborted
`
Is there anyway to adress it? 
Thanks in advance, 
Luis Alfonso.

**Comment by tobiasrausch** [comment]
If your kernel is too old then you need to compile from source or use one of the tracy containers for docker or singularity.
