### ISSUE TITLE
tracy: command not found

### ISSUE THREAD

**Issue by bomsterr** [gear-genomics/tracy#14]
I was able to install tracy on Linux and I ran `./tracy_v0.5.7_linux_x86_64bit -h` to open the software. The command line outputs saying "This is free software... etc.". I want to run an assemble and typed, `tracy assemble file1.ab1 file2.ab1` but get an error that says: "tracy: command not found." What am I doing wrong?

**Comment by tobiasrausch** [comment]
`./tracy_v0.5.7_linux_x86_64bit assemble file1.ab1 file2.ab1`

**Comment by bomsterr** [comment]
Thank you!

Also if I wanted to run this tracy command through various files in a directory, how would I write this?

**Comment by tobiasrausch** [comment]
If you want to run tracy for a bunch of ab1 files just use the absolute path to trace:

`for F in *.ab1; do tracy basecall -f fasta -o ${F}.fasta ${F}; done`
