### ISSUE TITLE
Can't download latest tracy 0.5.7 via conda

### ISSUE THREAD

**Issue by bomsterr** [gear-genomics/tracy#16]
I tried download Tracy on my conda as documented here: https://anaconda.org/bioconda/tracy.

However, this installs the old version (version: 0.5.3) and not the most recent 0.5.7 version. Is this a glitch on conda? I was able to download recent version as a statically linked binary.

**Comment by tobiasrausch** [comment]
That can happen if you have installed multiple tools in your conda environment and these request different versions of the dependencies. I am not sure how conda resolves these conflicts and in what order but in any case you can request a specific version using

`conda install -c bioconda tracy==0.5.7`

**Comment by bomsterr** [comment]
I tried your code and got the following error:

![image](https://user-images.githubusercontent.com/49420192/104043296-9bca9580-51a9-11eb-9721-dbe5c142d07b.png)

I am in my base environment though so I am not sure why tracy is conflicting with these other packages.

**Comment by tobiasrausch** [comment]
As I suspected, incompatible packages. I would either use the static binary or install a second, new conda environment.

**Comment by bomsterr** [comment]
okay thank you. Do you know what python version is compatible with Tracy?

**Comment by tobiasrausch** [comment]
Tracy is written in C++, it does not require python. The bioconda recipe states the dependencies:

[Tracy bioconda recipe](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/tracy/meta.yaml)

**Comment by jm245318** [comment]
![image](https://user-images.githubusercontent.com/50368123/104142294-f66e1800-5388-11eb-95de-53daa1f038b1.png)
I was also unable to install 0.5.7 in a clean conda environment.

**Comment by tobiasrausch** [comment]
Make sure you are outside any previous installed conda environment when you install a new one.

`conda deactivate`

Then you can install a new one, let's say in `~/testconda/`. I just tried this using Mac and Linux and it works fine.

Linux:

`wget 'https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh' && bash Miniconda3-latest-Linux-x86_64.sh -b -p ~/testconda && ~/testconda/bin/conda install -y tracy && ~/testconda/bin/tracy --version`

Mac OSX:

`wget 'https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh' && bash Miniconda3-latest-MacOSX-x86_64.sh -b -p ~/testconda && ~/testconda/bin/conda install -y tracy && ~/testconda/bin/tracy --version`

Can you please try this?

**Comment by muntajihad** [comment]
I tried your last code and I got this:

`  
sqlite             pkgs/main/linux-64::sqlite-3.33.0-h62c20be_0
  tk                 pkgs/main/linux-64::tk-8.6.10-hbc83047_0
  tqdm               pkgs/main/noarch::tqdm-4.51.0-pyhd3eb1b0_0
  urllib3            pkgs/main/noarch::urllib3-1.25.11-py_0
  wheel              pkgs/main/noarch::wheel-0.35.1-pyhd3eb1b0_0
  xz                 pkgs/main/linux-64::xz-5.2.5-h7b6447c_0
  yaml               pkgs/main/linux-64::yaml-0.2.5-h7b6447c_0
  zlib               pkgs/main/linux-64::zlib-1.2.11-h7b6447c_3


Preparing transaction: done
Executing transaction: done
installation finished.
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - tracy

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
`

**Comment by tobiasrausch** [comment]
You need to add the bioconda channel.

`conda install -c bioconda tracy=0.5.8`

**Comment by muntajihad** [comment]
this time I got:

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.                                                                                                                                     failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package xz conflicts for:
tracy=0.5.8 -> htslib[version='>=1.12,<1.13.0a0'] -> xz[version='>=5.2.4,<5.3.0a0|>=5.2.5,<5.3.0a0']
python=3.8 -> xz[version='>=5.2.4,<6.0a0|>=5.2.5,<6.0a0']

Package libgcc-ng conflicts for:
tracy=0.5.8 -> libgcc-ng[version='>=7.5.0|>=9.3.0']
tracy=0.5.8 -> bzip2[version='>=1.0.8,<2.0a0'] -> libgcc-ng[version='>=7.2.0|>=7.3.0']

**Comment by muntajihad** [comment]
following your instructions:
First I did:
`conda deactivate`
Then:
`wget 'https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh' && bash Miniconda3-latest-Linux-
x86_64.sh -b -p ~/testconda`
Then:
`~/testconda/bin/conda install -c bioconda tracy=0.5.8` 
And I got the error above

**Comment by tobiasrausch** [comment]
Thanks for reporting. I lately also had problems because of conda channel priorities as in this [issue](https://github.com/bioconda/bioconda-recipes/issues/17186). This should work as your last command:

`~/testconda/bin/conda install --strict-channel-priority --override-channels -c conda-forge -c bioconda -c defaults tracy`

Can you please try this?

**Comment by muntajihad** [comment]
Now it worked. Thank you very much. 
I have another question, if I may. when I run `tracy decompose` with whole reference genome (hg19) it says:
> Only single-chromosome FASTA files are supported.
And when I run it whith single reference genome (e.g. chr1 only), it says:
> Reference is larger than 50Kbp. Please use a smaller reference slice or an indexed genome!
what format of reference genome is needed?
Thanks

**Comment by tobiasrausch** [comment]
As written in the [documentation](https://www.gear-genomics.com/docs/tracy/cli/#genome-index), you need to download the reference genome indices [here](https://gear.embl.de/data/tracy/). This works for entire genomes. The FASTA option is only for small reference slices (<50kbp).

**Comment by muntajihad** [comment]
I have just noticed that. Thank you very much.

**Comment by tobiasrausch** [comment]
Thanks. Since the installation issue is fixed, I will close this issue. If you have further questions just open a new one.
