### ISSUE TITLE
sequence and qual not of the same length

### ISSUE THREAD

**Issue by tuspjo** [gear-genomics/tracy#17]
Hi, 
Thank you for a great tool. 
I am using it daily on 50-300 sanger files, and today one of the ab1 files produced sequence and qual score of different length in tracy basecall. the ab1file did not contain useful data, but I thought it might be relevant to report that tracy basecall can produce this issue. 
I can send you the ab1 file if you are interested?
I am using Tracy version: v0.5.3 (conda install)

**Comment by tobiasrausch** [comment]
We are happy to hear tracy is useful for your research. Can you please send us that trace file to rausch at embl.de

**Comment by tobiasrausch** [comment]
That appears to be fixed already. In tracy v0.5.7 it's working fine. That also the latest version in bioconda: [https://anaconda.org/bioconda/tracy/files](https://anaconda.org/bioconda/tracy/files)

**Comment by tuspjo** [comment]
Ok, thank you for your fast reply.

Best,

Tue

Den tir. 2. feb. 2021 kl. 21.39 skrev Tobias Rausch <
notifications@github.com>:

**Comment by tuspjo** [comment]
Hi again,
It seems that our install of tracy 0.5.7 does not solve the problem

 tracy basecall -f fastq -o badread.fastq test/badread.ab1; cat badread.fastq
[2021-Feb-03 08:17:21] tracy basecall -f fastq -o badread.fastq
test/badread.ab1
[2021-Feb-03 08:17:21] Done.
@primary
GGCCGGCCGCCCCACCAAAAGAAGATTGGGCGGGGCCTCAAACGGGGTTATGTTGGTTTTATTAGTTATGAGCGTTTAGCCCCAAACACAAATAAAAACAAAGTGAATTGAGATCCAGCACCCCGCCACGGCTGATTTTTAATACGGTCCTTTAGGTGGGGCCTCTTTCGGCTGGCAGCAGGGGGATAATGACTCATTGAACGAATGGACAAACATTCCATTCTAATGAACTGCCATTAGGCTCGGGCTCGGGACCCTCGCTCCGTGGGATGAAGAGCCCGACCACTTATGGACCGCCCCGTGCCCATGTTACGCAGACAAAAATGCACCACTTAGTAATCCATGGCATTTGAAAGCCGGCCCTATTCGGCTGATGGCACAGAGCGTCCGAATTGTGGCTGAGACTCCTACTGGTAGCTAAGTAGAGGCGTCTGATAAGCCCTTATCAATCGTAGATGTCCGTCACCCCTACATTACTAGGTGGTGGAGTTGCGGGAGCGGGANAACGNATTTCTTATTTGCTTGCCAAGCGATCTTGCATACATCCACATTCTGACCCTTTAAAAGGTGGTCGCAAGTAAGGGCACCGGGGGGGCCCCTCCACCGCCAAGGCCCAACTCCCTCCCACCGAGGGTCAGTTAACCCTAATGGCGCGCAGCGGATGCTTCACAATGGGGGGGGTATAATTNCCAAATGAGCCGCTTAGTTAGNCAGAACCCTCTAAGAGTGGTTCACCGCAGGTTGTCCTATAGCGTCATGAACCCATTGCACGGATCATCTGAAGTTGCCAATGTGATTAATTTCCCATTAACGAGGTCACCCAGGCCGGCCACTTAACTACGTGCGTTGAGTAGGTGCTACGCGACTACCACATCAGCTATTGAGGCCACCCTAACGTTAACCATTAGTGTCAAAAAGATGAAGGCTGCCGTGGGCATTCCCAAGCGTTGTTTTTTGTGGGGTGATCTCGATGGTAATGAATATTTCTTTTCTTGGGCTCTAAGGNAAAAAGGCAAGA
+
$$$$#%*%%$$$$$$$$#$$(,$$$#(*)%-0)*))$$&$,-1#',*$083877778;GF?8?3/+1/5517594(#$$')#+**((2(1//7412/21*)*,,$$#$1(/2*6-*/$)&#'*$$*(127#&&&-'00146(&&&,++65)#(/06@C


8:18 <https://biosustain.slack.com/archives/C01KQ65KQ4C/p1612336704119600>

❯ tracy --version
Tracy version: v0.5.7
 using Boost: v1.70.0
 using HTSlib: v1.10.2


Den ons. 3. feb. 2021 kl. 08.36 skrev Tue Sparholt Jørgensen <
tuesparholt@gmail.com>:

**Comment by tobiasrausch** [comment]
Sorry, I only checked the tsv file which looked fine. Anyway, I could debug it now. Indeed a very subtle error that apparently can happen with very low quality traces. It's fixed now in the code repository. Thanks for reporting the bug and sharing the trace file!
