### ISSUE TITLE
Peak percentage cut off

### ISSUE THREAD

**Issue by mcrone** [gear-genomics/tracy#18]
Thank you for the awesome tool! I'm using it to deconvolute SARS-CoV-2 Sanger data and I've found that sometimes I get erroneous variant calls because of some underlying noise in one of the reads that is not present in the other read.

For example if you look at the sequence AAACTG there is some underlying noise in the forward read (bottom) but not the reverse read, or there is contrasting noise that should really cancel out, but sometimes is called as a variant.
![image](https://user-images.githubusercontent.com/4923807/109740852-dbb76300-7bc3-11eb-9526-2855e878bcc4.png)

Ideally I would like to use Tracy like the Indigo tool (but I want to be able to have forward and reverse reads) and I would like to be able to tune the peak percentage cut off.

And another question, is there a way to have automatic annotation of Amino acids in the vcf file? I see that this is done in similar pipelines with bcftools and a gff file.

**Comment by tobiasrausch** [comment]
[Indigo](https://github.com/gear-genomics/indigo) runs [tracy](https://github.com/gear-genomics/tracy) in the backend using these command-line parameters:

`tracy decompose -v -r SARS-CoV-2.NC_045512.2.dna.fa.gz -q <left_trim> -u <right_trim> -p <peak_ratio> -o <output_prefix> <input.ab1>`

As far as I know Sars-CoV-2 is not yet included in the Ensembl REST API but [tracy](https://github.com/gear-genomics/tracy) outputs a standard VCF/BCF file. [Indigo](https://github.com/gear-genomics/indigo) also allows you to download that BCF file on the results tab. What you can do with this BCF file is, for instance:

`bcftools view indigo-variants.bcf | grep -v "^#" | cut -f 2-5 | awk '{print "NC_045512.2\t"$0;}'`

The output you can simply paste into the [Ensembl VEP Tool](https://covid-19.ensembl.org/Sars_cov_2/Tools/VEP) to get amino acid annotation.

Merging of multiple trace files, like forward and reverse, is possible with [Pearl](https://www.gear-genomics.com/pearl/).

**Comment by mcrone** [comment]
Thank you! That is incredibly helpful!
