### ISSUE TITLE
Failing to create reference due to lack of RAM

### ISSUE THREAD

**Issue by OgnjenMilicevic** [gear-genomics/tracy#2]
Hi!

I tried to create a fm9 file for the hg38, but the program quickly ate up all the 16GB of available RAM and killed the process. Is this normal behavior?

The file was in fasta.gz format.

Thanks!

**Comment by tobiasrausch** [comment]
Index creation for mammalian-sized genomes requires ~64G RAM. This is only required once, the actual program then runs with ~8G RAM. You can download the index file for [GRCh38 here](https://gear.embl.de/data/tracy/).
