### ISSUE TITLE
rs identifiers 

### ISSUE THREAD

**Issue by Kanyerezi30** [gear-genomics/tracy#21]
Hello here,
I am working with tracy v0.5.3 on the commandline to call variants. I first downloaded a selected section of the human genome as the reference. On calling the variants, the results don't have the rs identifiers yet the web results give the rs identifiers

I thought i would resort to the full human genome reference (GRCH38) but this returned the error below
"terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc"

**Comment by tobiasrausch** [comment]
Looks like your machine has not enough memory (RAM). For rs identifiers you indeed need to use full genomes but that requires ~4G RAM.

`tracy decompose -v -a homo_sapiens -r Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz input.ab1`

**Comment by Kanyerezi30** [comment]
But the machine has 16GB RAM

**Comment by tobiasrausch** [comment]
Then it should be fine. Can you try the latest tracy version? We switched the indexing at some point and maybe that's causing the bad allocation.

**Comment by Kanyerezi30** [comment]
Thanks a lot for your timely response.
I will be trying that then

**Comment by Kanyerezi30** [comment]
I created a new conda environment with tracy v0.5.9 and it finally worked

Thanks a lot for the help
