### ISSUE TITLE
consensus not obtained from majority of bases present

### ISSUE THREAD

**Issue by bomsterr** [gear-genomics/tracy#27]
I assembled the contigs with a reference to obtain the consensus shown below. However, the consensus generated a "A" where there was supposed to be a "G", based on majority rule. Is there a way I can make consensus generate a "G" based on the majority of bases present? some paramters I can set somehow?

![image](https://user-images.githubusercontent.com/49420192/122079603-92ce9780-cdcb-11eb-898b-04ae0a66e91c.png)

**Comment by tobiasrausch** [comment]
Hi,

The reference is only used to guide the assembly. In the consensus computation we currently only consider the trace files. In the above case this causes a tie between A and G which is resolved randomly. We could introduce a new command-line option (--incref) to include the reference for the consensus computation, that's maybe helpful in some scenarios?

Best, Tobias

**Comment by bomsterr** [comment]
Hi Tobias, 

That would be amazing and incredibly useful to the end users!!! Thank you so much for the idea to add this new feature. 

Would this be part of the new version and do you know what the timeline would be? No rush -- was just curious!

Sincerely,
Bomi

**Comment by tobiasrausch** [comment]
Hi,

You can now specify `--incref` to include the reference in the consensus computation (to break ties for instance).

`tracy assemble --incref -r reference_slice.fa forward.ab1 reverse.ab1`

Best, Tobias

**Comment by bomsterr** [comment]
Hi Tobias,

I updated to the most version of tracy (v0.5.9) and tried your line of code but I got the following error:
 `unrecognized option '--incref'`
