### ISSUE TITLE
tracy assemble options.

### ISSUE THREAD

**Issue by YoungYu5** [gear-genomics/tracy#29]
hello.
I assemble to sanger sequences used tracy assemble.
however, I want to use this tools myself, but I don't understand all of options.
so, i find manual in tracy github and paper, there was no mention of an explanation anywhere.
I want to know these options detaily.
1. The basis of the trim option. Trim option (-t) range is 1~9. is this value mean peak value or first length? or any other value? please explain this options.
2. I want to assemble sequence to use peak value. In this tools (tracy assemble), any options select sort peak options?

Thanks.
young yu.

**Comment by tobiasrausch** [comment]
Hi,
tracy assemble can potentially assemble dozens of traces and that makes it cumbersome to define a trimming length for each input trace. Instead, tracy assemble uses '-t' which specifies a trimming stringency, with 1 being the most aggressive trimming and 9 being almost no trimming.
I am not sure about your second question. We don't assemble 'peaks', it's just about generating consensus nucleotides for each trace and then it's a multiple-sequence alignment problem that tracy assemble solves.
Best, Tobias

**Comment by YoungYu5** [comment]
Sorry to late reply.
I understood trimming option and tracy assemble algorithm.
Thanks!
