### ISSUE TITLE
Returning error code from bcftools

### ISSUE THREAD

**Issue by OgnjenMilicevic** [gear-genomics/tracy#3]
I created a malformed reference file that had a whitespace after ">". When trying to write the variant in the file, BCFTOOLS returned ID -1 error and the variant didn't appear in the final BCF. Still, tracy returned error code 0.

Is there any way that tracy could somehow signal this in the error code, as well as any other problem that might arise? No need for specifics, just a non-zero code. If this is missed, I think there is no way to differentiate the homozygous reference call from this error.

**Comment by tobiasrausch** [comment]
Unfortunately, the [VCF spec](https://samtools.github.io/hts-specs/VCFv4.2.pdf) is not entirely clear to me regarding which special characters are allowed in chromosome names. For instance, the sentence "The colon symbol (:) must be absent from all chromosome names…" disagrees with the HLA contigs in GRCh38. I frankly don't have a conclusive answer to this problem, for the time being tracy strips all \ , "'`` () <> [] {}# characters from chromosome names but not spaces. This might change in the future, I am not sure. In general, I would recommend simple alphanumeric chromosome names without special characters.

**Comment by OgnjenMilicevic** [comment]
Is this the only instance of errors you expect returned from BCFTools? I am quite ok with adhering to certain naming conventions (in files as well, I noticed the input files with whitespaces raise errors). I am more worried about missing an error in the printout, while the error code is 0.
