### ISSUE TITLE
--incref (to break consensus ties) is not a feature yet

### ISSUE THREAD

**Issue by bomsterr** [gear-genomics/tracy#30]
Hi Tobias,

I know you added in the --incref feature to include reference in the consensus computation. However, I upgraded to most recent tracy and the --incref is still not an accessible feature. Do I have to manually install this feature somehow?

**Comment by tobiasrausch** [comment]
Hi,

I updated the code repository but I see that you need a new release. That's fine, there is now a new version [v0.6.1](https://github.com/gear-genomics/tracy/releases) also available on Bioconda or as Docker/Singularity container.

Best, Tobias
