### ISSUE TITLE
consensus sequence in out.vertical file

### ISSUE THREAD

**Issue by nukaemon** [gear-genomics/tracy#33]
Hello

I have install v0.6.1 to assemble forward and reverse Sanger sequences.
Because a source of the sequences is a cloning vector, I need to compromise mismatch sites between forward and reverse overlaps(that is, no heterozygous site is expected).
I think I should do this based on quality information, but now I'm wondering if an out.vertical file is the one I'm looking for.
My question is whether the consensus sequence(the most right character) in out.vertical file always chooses the one with higher quality.

(example)
-T|T
-C|C
-A|A
-A|A
-A|A
GG|G
AA|A
AA|A
GG|G
TT|T
CC|C
TT|T
**AC|A**  <- is this A chosen because its quality is higher than C?
CC|C
CC|C

**Comment by tobiasrausch** [comment]
The consensus computation is a simple majority vote and a tie is broken arbitrarily. You can include a reference sequence (`--incref`) in the consensus computation (to break ties for instance) but qualities are currently not taken into account.

**Comment by nukaemon** [comment]
Thank you for quick reply, @tobiasrausch.
I understand.

Using reference doesn't work in my case because th sequence is a hypervariable region of antibody.
Anyway, I will extract quality information from fastq or tsv file from 'basecall', but in the future version, I appreciate if 'assemble' gets able to leave quality information in out.vertical or out.json files.
