### ISSUE TITLE
Consensus not assembling properly

### ISSUE THREAD

**Issue by bomsterr** [gear-genomics/tracy#35]
Hi,

I put in two .ab1 files and a reference file to generate a consensus. Tracy wasn't able to generate the proper nucleotide base as shown below (there is a "T" where there should be an "A" if this is based on majority rule.) I am wondering what the problem is, thank you.

![image](https://user-images.githubusercontent.com/49420192/124664492-893fc900-de79-11eb-91a1-0c84ddf91e29.png)

**Comment by tobiasrausch** [comment]
This looks indeed strange. Can you please share the 2 trace files and the reference slice then I can debug? Maybe a problem with the recently added --incref option.
