### ISSUE TITLE
How is a strand orientation in de novo assemble outputs determined?

### ISSUE THREAD

**Issue by nukaemon** [gear-genomics/tracy#36]
Hello

To assemble forward and reverse ab1 files from Sanger sequence, I executed assemble command without reference (i.e. de novo assemble) like

`$ tracy assemble forward.ab1 reverse.ab1`

and expected that the aligned fasta display sequences in the same strand and direction as forward would be, but in fact, it followed in reverse strand manner.
It seems like it is not determined at random because I always get outputs in reverse strand manner, and when I switched the order of arguments, that is, reverse.ab1 first and forward.ab1 second, I got the aligned fasta in forward strand manner.

So, I guess that a strand orientation in de novo assemble outputs is always based on the last ab1 file given in command line.
Is this correct?

**Comment by tobiasrausch** [comment]
Without a guiding reference there is no defined output strand. This depends on the multiple-sequence alignment guide tree which in turn depends on the pairwise trace similarities. I believe for the special case of only two input traces you are right.

**Comment by nukaemon** [comment]
Thank you so much for clarifying.
It might be helpful at least in my case if an option is available to explicitly define an output strand by specifying one of the input ab1 files as standard.

**Comment by tobiasrausch** [comment]
You can in fact do this by first basecalling the "standard" trace (fwd.ab1 below)

`tracy basecall -f fasta -o ref.fasta fwd.ab1`

and then using this sequence as the "reference"

`tracy assemble -r ref.fasta fwd.ab1 rev.ab1`

because then all traces are aligned against the reference.

**Comment by nukaemon** [comment]
Aha, you're right.
Thank you for your helpful comment!
