### ISSUE TITLE
Not human samples

### ISSUE THREAD

**Issue by Kanyerezi30** [gear-genomics/tracy#37]
Hello,
I have used tracy to call and annotate variants from human samples and it worked well. I have sanger sequenced samples of P.falciparum.
I am inquiring if there's a way i could use tracy to call and annotate these samples

**Comment by tobiasrausch** [comment]
Hi,

On the command-line tracy just outputs a standard VCF file. You can then annotate these variants using VEP for your organism:

[P. falciparum VEP](https://protists.ensembl.org/Plasmodium_falciparum/Tools/VEP)

Best, Tobias

**Comment by Kanyerezi30** [comment]
Thank you,
This has worked so well
