### ISSUE TITLE
How to get the name out of a trace file?

### ISSUE THREAD

**Issue by FadiBakoura** [gear-genomics/tracy#38]
I used the following command:  

```shell
tracy basecall -f json -o output_file_path input_file_path
```  

I expected to get the name (identifier) in the output json file.  

It would be useful if I can get the name using the same above API

**Comment by FadiBakoura** [comment]
May I ask also how to get `quality numbers`

**Comment by tobiasrausch** [comment]
The quality values are only available in the tsv output at the moment:

`tracy basecall -f tsv -o out.tsv <input.ab1>`
