### ISSUE TITLE
Tracy assemble time

### ISSUE THREAD

**Issue by nriddiford** [gear-genomics/tracy#39]
This is not so much of an issue, but I just wanted to dig a bit into expected completion times for `tracy assemble`. 

I'm running `tracy assemble` (de novo assembly) on 4 `.ab1` files, each with around 1Kb of high quality calls. The sequenced construct is ~2Kb (so there's a lot of overlap between the 4 `.ab1` files 

Here's the command I'm running:

`tracy assemble primer_f_1.ab1 primer_f_2.ab1 primer_r_1.ab1 primer_r_2.ab1 --format fastq`

This takes around 2 minutes to complete, which seems like a long time. Is this expected?

**Comment by tobiasrausch** [comment]
Tracy computes a progressive multiple sequence alignment using profiles of the input chromatogram traces. I think the complexity is O(k^2 * n^2 + k^3) with k being the number of traces and n the length.
