### ISSUE TITLE
Old index data format. Please rebuild your reference genome index!

### ISSUE THREAD

**Issue by yangmqglobe** [gear-genomics/tracy#4]
I got this issue on the latest code when try to decompose a sanger seq result, what is the matter? Is this a samtools version related issue?

**Comment by tobiasrausch** [comment]
Hi,

You just need to rebuild your reference index

`tracy index -o hg38.fa.fm9 hg38.fa.gz`

We had to change the indexing data structures because of licensing issues. The new indexing creates 2 files and both files need to be in the same directory.

`hg38.fa.fm9`
`hg38.fa.fm9_check`

**Comment by tobiasrausch** [comment]
I hope this solved your problem. Closing this issue for the time being.
