### ISSUE TITLE
Can Tracy train itself to take into account previously identified alleles? 

### ISSUE THREAD

**Issue by SheepwormJM** [gear-genomics/tracy#44]
Hi,

I'm looking to use Tracy to decompose alleles from several hundred sequence traces. It looks like a very useful tool - thanks for writing it.

My organism is quite heterozygous. I could expect that there would be more than one (many) variants within an allele.

Am I understanding that during decomposition it takes the first haplotype to be the closest match to the reference sequence, and denotes all other mutations present to the second haplotype? 

Is it possible to instead ask it to:
1. Do this for all traces
2. Then re-assess - starting with paired haplotypes with low levels of mutations (perhaps even one which is identical to the reference and the other with a single SNP for example) to identify potentially a pair of haplotypes in another sample, where each has mutations relative to the reference - for example one might have one or two SNPs, commonly found as a haplotype in other samples, while the other haplotype has an indel and a third SNP... 

Does the pearl command work this way? Or does it just align already decomposed sequences/primary basecalls from a non-decomposed sequence?

I realise either way it is still guessing the haplotype for the sequence. 

Many thanks,
Jenni

**Comment by tobiasrausch** [comment]
Traces don't provide haplotyping information and therefore, tracy indeed first threads the reference through the peaks and whatever is left constitutes the second allele. You can also compare traces directly without a reference, e.g., a wildtype trace against a mutated trace. Pearl (the assemble subcommand) is essentially a multiple trace alignment, either against a reference (reference-guided assembly) or de novo. It's useful to find "common" alleles that are in many traces but not in the reference.
