### ISSUE TITLE
SCF version greater 2.9 required!

### ISSUE THREAD

**Issue by blex-max** [gear-genomics/tracy#51]
I am trying to assemble some old (c.a. 2010) Sanger traces and I'm logging the following error.

```
[2022-Feb-17 15:06:11] tracy assemble --inccons -o data0/tracy_assemble/6_512_1A04 ./data0/traces/6_512_1A04_ITS4_R0.ab1 ./data0/traces/6_512_1A04_ITS1F_R0.ab1 
[2022-Feb-17 15:06:11] Load ab1 files
SCF version greater 2.9 required!
```

Why is this the case, and is there any way we can work around this? In my opinion, it's a limitation to Tracy since so much .ab1 data is now old/outdated.

Thanks for maintaining Tracy!

**Comment by blex-max** [comment]
Thank you for the pointer. It seems the Staden program trev can convert from the old standard, but it's not a documented use case and it can only, as far as I can tell, do one file at a time! I have posted on their discussion forum but the last active post was 2020 so I'm not sure if I'll get a response. Does Tracy use any of the Staden libraries out of interest?

**Comment by tobiasrausch** [comment]
Tracy relies on Boost, HTSlib and SDSL. It is not using the Staden library.

**Comment by blex-max** [comment]
Solved using undocumented utility scf_update in the Staden io library - https://github.com/jkbonfield/io_lib/tree/io_lib-1-14-1, close if you like, I've left it open as I feel like it might be useful info for others
