### ISSUE TITLE
Only single-chromosome FASTA files are supported

### ISSUE THREAD

**Issue by asaki1986** [gear-genomics/tracy#52]
Hi,

I am using Tracy (Version: 0.7.1) to call SNVs from sanger sequencing ab1 files

Command is listed as follows,
./tracy decompose -o forward -a homo_sapiens -r /bioinfo/data/Genomes/NCBI/build37/Sequence/WholeGenomeFasta/human_g1k_v37.fasta GW21T135C07-2_K-E11-F_TSS20210511-021-02103_G01.ab1

However, "Only single-chromosome FASTA files are supported" was returned, and bcf file was not generated as expected.

Any suggestions to fix the issue?

Thanks,
Junfeng

**Comment by tobiasrausch** [comment]
That's described in the [tracy documentation](https://www.gear-genomics.com/docs/tracy/cli/#genome-index). You can either use a pre-built genome index for human, a small FASTA sequence that is indexed on the fly or a wildtype chromatogram.

**Comment by asaki1986** [comment]
I built the genome index using commands suggested.

After getting the .fm9 file, I re-run de command, still get the "Only single-chromosome FASTA files are supported" message.
