### ISSUE TITLE
Decompose doesn't give bcf file give json instead

### ISSUE THREAD

**Issue by rahulAAI** [gear-genomics/tracy#54]
tracy decompose -v   -o outprefix  -g  ref.fna  Sample.ab1
used this command for variant calling, getting a json file but no bcf

**Comment by tobiasrausch** [comment]
The genome is specified with `-r` and not `-g`. Your command should be:

`tracy decompose -v -o outprefix -r ref.fna Sample.ab1`

This command generates `outprefix.json` and `outprefix.bcf` among other files.

Please also check you are using the latest tracy version (v0.7.1):

`tracy -v`

**Comment by rahulAAI** [comment]
Thank you, the version upgrade worked .
but now i am facing a new problem. 
 tracy index -o ref.fa.fm9 ref.fna
does not produce a ref.fa.fm9 file 
i have tried indexing with samtools faidx and the using this command as well
Thank you for your help

**Comment by tobiasrausch** [comment]
The genome `ref.fa` needs to be bgzipped ([htslib](https://github.com/samtools/htslib)) and indexed with samtools ([samtools](https://github.com/samtools/samtools). 

`bgzip ref.fa`
`samtools index ref.fa.gz`
`tracy index -o ref.fa.fm9 ref.fa.gz`
