### ISSUE TITLE
How can I provide a file with a list of input files to tracy?

### ISSUE THREAD

**Issue by SheepwormJM** [gear-genomics/tracy#59]
Hi,

This might be a very basic question, but I can't see how to do it in the manual help files. I would like to provide tracy with over 200 .abi input files at one go. Is it possible to provide a file containing a list of all input files rather than having them listed separately within the input command? 

Thanks,
Jenni

**Comment by tobiasrausch** [comment]
Just loop over all files

`for FILE in *.ab1; do ls ${FILE}; done`
