### ISSUE TITLE
Indigo

### ISSUE THREAD

**Issue by Donandrade** [gear-genomics/tracy#61]
I'm using the FASTA sequence (single sequence, as you can see in the image below) as a reference, to align my *ab1 file using the Indigo module (https://www.gear-genomics.com/indigo/). But, I don't know why the program it's returning the message:  "Fasta file has incorrect file type!".  Could you help me solve this problem?

My fasta file looks like this:
![image](https://user-images.githubusercontent.com/3967276/165939099-910ed2f6-fb29-4bfa-8f14-25979668d8a4.png)

**Comment by tobiasrausch** [comment]
It's probably a file naming issue. Fasta files have to end with ".fa" or ".fasta" like "reference.fa", for instance.

**Comment by Donandrade** [comment]
Thanks, dear Tobias!
It could be that the problem, but my file has the end with ".fasta", as you can see below indicated by red arrows:
![image](https://user-images.githubusercontent.com/3967276/165943643-b4691a85-9fa8-4828-a55d-1a687a89fe2d.png)

**Comment by tobiasrausch** [comment]
Sorry, that was a different problem with our backend server. There was an IT networking issue. Can you please try again?

**Comment by tobiasrausch** [comment]
I hope this is working now. If that's not the case please re-open the issue.
