### ISSUE TITLE
Cannot execute Tracy binary on mac

### ISSUE THREAD

**Issue by blex-max** [gear-genomics/tracy#62]
I'm trying to get Tracy to run (as part of a pipeline we're using in our lab) on a macOS catalina system. Unfortunately the binary can't execute on a mac - I imagine perhaps it simply wasn't designed to run on mac, but do you perhaps have any suggestions on how to get around this?

**Comment by tobiasrausch** [comment]
Tracy works on Mac OS. You can use for instance the [conda Mac OS version of tracy](https://anaconda.org/bioconda/tracy).

**Comment by blex-max** [comment]
Thanks very much - this might be a fix, but I see that the version of Tracy available on Conda is only v0.5.3 despite the label on the webpage. It does not have the consensus command!

**Comment by blex-max** [comment]
Apologies, that was my mistake in my install - I'll close this as soon as I can be sure it's running properly. Thanks for your help!

**Comment by tobiasrausch** [comment]
On the first execution the conda environment needs to be loaded. After that the performance should be very similar on comparable hardware. I anyway bumped the version now on bioconda (tracy=0.7.2) because I wasn't sure if the consensus subcommand was already part of the previous release.
