### ISSUE TITLE
Bioconda tracy package runs very slowly where precompiled binary is fast

### ISSUE THREAD

**Issue by blex-max** [gear-genomics/tracy#63]
Per #62, running the bioconda tracy package is really slow for the consensus command at approx ~15s per run compared to about ~1 for the precompiled binary. I am calling tracy in a bash pipeline, within a loop and having activated the conda env prior to the loop, in the following way:

```
    if
    tracy consensus \
    -o "$out_dir"/assembly/"$code"_cons \
    -q 0 -u 0 -r 0 -s 0 \
    -b "$code" \
    "$ffile" \
    "$file" \
    >> "$out_dir"/logs/basecall_log.txt 2>&1
    then

    ...
```

The only thing that changes to use the precompiled binary is `tracy consensus` becomes `./tracy/tracy consensus`. It is unclear to me why this change would result in such a massive slowdown. I could avoid the bioconda package, but I cannot get the precompiled binary to run on mac. Thanks!

I am perfoming testing on Ubuntu 20.04 with Tracy 0.7.1

**Comment by tobiasrausch** [comment]
Mac OS X doesn't support static binaries. You can either compile from source on Mac OS X or try the tracy docker / singularity containers if these are faster than the conda version.
