### ISSUE TITLE
terminate called while attempting to run tracy on WSL

### ISSUE THREAD

**Issue by blex-max** [gear-genomics/tracy#64]
I cannot get tracy consensus to run on certain .ab1 files on a colleagues WSL install. I can however get them to run on a native linux install. The error is the following:

```
terminate called after throwing an instance of 'std::length_error'
what(): cannot create std::vector larger than max_size()
```

I've attached a pair of traces from the failing batch below
[004_B05.zip](https://github.com/gear-genomics/tracy/files/8632550/004_B05.zip)

**Comment by tobiasrausch** [comment]
Tracy does not run on Windows and we also do not support Windows Subsystem for Linux (WSL). The docker container might still work under Windows.
