### ISSUE TITLE
Basecall on ab1 files with empty corrected signals (DATA9-12)

### ISSUE THREAD

**Issue by bdolmo** [gear-genomics/tracy#7]
Hello,
I have a bunch of AB1 files without corrected intensity levels, so only data on fields DATA1-4.
When I try tracy on these files I am getting a segfault error. 
Do you know if it is possible to perform basecalling on them? I suspect I will have to generate them again.

Thanks!

**Comment by tobiasrausch** [comment]
Hello,

Tracy needs the basecalling positions. Trace signals alone (DATA) is not sufficient.

Best, Tobias
